"""Shared session limits and lifecycle and observation defaults."""

from datetime import timedelta


MAX_MESSAGE_LENGTH = 16_000
MAX_MESSAGE_COUNT = 200
MAX_ARTIFACT_HEADER_LENGTH = 200
MAX_ARTIFACT_DESCRIPTION_LENGTH = 2_000
MAX_OBSERVERS_PER_SESSION = 8
MAX_PENDING_OBSERVATION_UPDATES = 128
OBSERVATION_REFRESH_INTERVAL_SECONDS = 10
DEFAULT_SESSION_LIFETIME = timedelta(minutes=90)
